### ISSUE TITLE
Committee OpenAPI 3 locked to version 3.0.x

### ISSUE THREAD

**Issue by hedselu** [interagent/committee#303] opened 2021-04-08 09:08 UTC
Hi!

First of all, thanks for great gem. I just found a problem when I upgrade OpenAPI version in document to 3.1.0. 
The current implementation has locked version to 3.0.x, and fails finding paths for this document.

Current behaviour:
- runs HyperSchema driver for version OpenAPI version 3.x.x

Expected behaviour:
- runs OpenAPI3 driver for version OpenAPI 3.x.x

Related committee file for this issue: https://github.com/interagent/committee/blob/v4.3.0/lib/committee/drivers.rb#L52
Latest version of OpenAPI changelog: https://github.com/OAI/OpenAPI-Specification/releases

**Comment by ota42y** [comment] 2021-04-08 10:55
Thank you for reporting!
However, committee doen't support OpenAPI 3.1.0 yet.
(I have not been able to verify that it works properly)

So we can't load OpenAPI 3.1.0 now sorry

**Comment by hedselu** [comment] 2021-04-08 11:01
@ota42y understandable, thank you for answering!

Let me know if I should try verifying support for 3.1.x or someone else might take care of this. Of course I'd be happy to contribute.

**Comment by ota42y** [comment] 2021-04-08 11:04
I haven't check the OpenAPI 3.1.0 specification yet, so I haven't decided how much modification is needed ... 🙇

**Comment by hedselu** [comment] 2021-04-08 11:22
@ota42y no problem, thanks for response! 🙏

**Comment by ahx** [comment] 2023-04-03 18:43
One of the main differences with 3.1 and committee that I have noticed is the `type` field in JSON Schema. In 3.0 (and legacy JSON Schema version) it only accepts a string like `type: integer`, but in 3.1 (and at least JSON Schema draft-7) it support lists as well like  `type: [integer, string]` or even `type: [integer, null]` (which replaces `nullable`).

https://github.com/davishmcclurg/json_schemer supports draft-7.

**Comment by chrishough** [comment] 2024-11-05 23:45
@ahx that type nullable is really nice

**Comment by geemus** [comment] 2024-11-06 01:49
I've been working on compiling notes on changes that will be needed. I think also that we can probably add a little at a time (ie we don't have to wait to support all of 3.1 before we support parts). It may still take a little while though and I'd certainly welcome help from others to keep moving it forward.

**Comment by geemus** [comment] 2024-11-08 14:44
Hey, I agree that 3.1 would be great to continue working toward. That said, I think this is at least mostly a duplicate of #352. So I'm going to close this in favor of consolidating discussion in one place. I'd welcome folks to continue adding their questions and thoughts over there.

**Closed by geemus** 2024-11-08 14:44 UTC
